config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks'}

  root to: 'events#index'

  resources :users do
    resources :availabilities
  end

  resources :availabilities, only: ['new', 'create', 'index', 'destroy']

  resources :events do
    member do
      post :attend
      delete :cancel
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:twitter]
  has_many :attendances
  has_many :availabilities, dependent: :destroy

  validates :name, presence: true

  acts_as_taggable_on :interests

  accepts_nested_attributes_for :availabilities

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      config_attributes(user, auth)
    end
  end

  def email_required?
    super && provider.blank?
  end

  def self.config_attributes(user, auth)
    user.name = auth.info.name
    user.password = Devise.friendly_token[0, 20]
    user.image = auth.info.image
    user.screen_name = auth.info.nickname
  end
end

app/controllers/api/users_controller.rb
module API
  class UsersController < API::ApplicationController
    def me
      authorize! :show, current_user

      render json: current_user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  authorize_resource
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    authorize! :manage, @user
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: 'Account created with success.'
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(users_params)
      redirect_to user_path(@user), notice: 'Account updated with success.'
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to 'index'
  end

  def users_params
    params.require(:user).permit(:name, :location, :gender, :interest_list, :screen_name)
  end
end

app/views/users/_fields.slim
.Form
  .Form-item
    = f.label :name
  .Form-item--input
  = f.text_field :name
  .Form-item
  = f.label :location
  .Form-item--input
  = f.text_field :location
  .Form-item
  = f.label :gender
  .Form-item--input
  = f.text_field :gender, collection: [:female, :male]
  .Form-item
  = f.label :interest_list
  .Form-item--input
  = f.text_field :interest_list, value: @user.interest_list.join(',')
  .Form-item
  = f.submit

app/views/users/edit.slim
h2 Edit Profile

= form_for @user do |f|
  = render partial: 'fields', locals: {f: f}

= link_to 'Profile', user_path(@user)

app/views/users/index.slim
h1 Users

table
  tr
    th Name
    th Email
    th Location
    th Gender
    th &nbsp
  -@users.each do |user|
    tr
      td =link_to user.name, user_path(user)
      td =user.email
      td =user.location
      td =user.gender
      -if can? :destroy, @user
        td =link_to 'delete', user_path(user), method: :delete

app/views/users/show.slim
.BodyLayout
  .BodyLayout-header
    .BodyLayout-headerItemCenter
      .Heading.Heading--large = "@#{@user.screen_name}"
  .BodyLayout-content
    .Grid.Grid--twoColumns
      .Grid-item
        .Heading.Heading--small
          | Availability
        .Separator
        .ContentLayout
          ul.List
            -@user.availabilities.each do |availability|
              li.List-item
                .TextWithIcon.TextWithIcon--delete
                  .TextWithIcon-text
                    = "#{Date::DAYNAMES[availability.week_day]}'s from #{availability.start_hours} up to #{availability.end_hours}"
                  = link_to user_availability_path(@user, availability), method: :delete, class: 'TextWithIcon-icon' do
                    span.fa.fa-close
          .ContentLayout-action
            = link_to 'add availability', new_user_availability_path(@user), class: 'Button Button--super'
      .Grid-item
        .Heading.Heading--small
          | Interests
        .Separator
        .ContentLayout
          ul.List
            -@user.interest_list.each do |interest|
              li.List-item
                .TextWithIcon.TextWithIcon--delete
                  .TextWithIcon-text
                    = "#{interest}"
                  = link_to '#', method: :delete, class: 'TextWithIcon-icon' do
                    span.fa.fa-close
          .ContentLayout-action
            = link_to 'add interest', '#', class: 'Button Button--super'