config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks'}

  root to: 'events#index'

  resources :users do
    resources :availabilities
  end

  resources :availabilities, only: ['new', 'create', 'index', 'destroy']

  resources :events do
    member do
      post :attend
      delete :cancel
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :attendances, dependent: :destroy

  validates :name, presence: true
  validates :location, presence: true
  validates :start_date, presence: true

  acts_as_taggable_on :interests

  after_create :notify_users

  scope :future, -> { where('start_date >= ?', Time.now).order('start_date ASC') }

  def attending?(user_id)
    Attendance.find_by(user_id: user_id, event_id: id).present?
  end

  def starting_date
    "#{start_date.strftime('%d/%m/%Y')} at #{start_date.strftime('%H:%M')}"
  end

  def notify_users
    EventNotifications.perform_async(id)
  end

  def attend(user_id)
    Attendance.create(event_id: id, user_id: user_id) unless existing?(user_id)
  end

  def cancel(user_id)
    Attendance.where(user_id: user_id, event_id: id).first.destroy
  end

  private

  def existing?(user_id)
    Attendance.where(user_id: user_id, event_id: id).any?
  end
end

app/controllers/api/events_controller.rb
module API
  class EventsController < API::ApplicationController
    skip_before_action :authenticate, only: [:index, :show]
    skip_authorization_check :only => [:index, :show]

    def index
      render json: Event.all
    end

    def show
      render json: Event.find(params[:id])
    end

    def attend
      @event = Event.find(params[:id])
      authorize! :create, Attendee

      if Attendee.attending?(current_user.id, @event.id)
        Attendee.create(user_id: current_user.id, event_id: @event.id)
      end

      render json: @event
    end

    def cancel_attend
      @event = Event.find(params[:id])
      authorize! :create, Attendee

      unless Attendee.attending?(current_user.id, @event.id)
        Attendee.find_by(user_id: current_user.id, event_id: @event.id).delete
      end

      render json: @event
    end

    private

    def event_params
      params.require(:event).permit(:name, :location, :start_date, :end_date, :description, :hashtag, :interest_list).merge(owner: current_user.id)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  authorize_resource

  def index
    @events_per_month = Event.future.group_by { |event| event.start_date.month }

    respond_to do |format|
      format.html
      format.json { render json: Event.future }
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
    authorize! :manage, @event
  end

  def create
    @event = Event.new(event_params)
    @event.owner_id = current_user.id

    if @event.save
      redirect_to event_path(@event), notice: 'Event Created Sucessfully'
    else
      render 'new'
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to event_path, notice: 'Event Updated Sucessfully'
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path
  end

  def attend
    @event = Event.find(params[:id])

    @event.attend(current_user.id)  unless @event.attending?(current_user.id)

    redirect_to event_path(@event)
  end

  def cancel
    @event = Event.find(params[:id])

    if @event.attending?(current_user.id)
      @event.cancel(current_user.id)
    end
    redirect_to event_path(@event)
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :start_date, :end_date, :description, :hashtag, :interest_list)
  end
end

app/views/events/_fields.slim
.ContentLayout
  .ContentLayout-label
    = f.label :event_name, class: 'Label'
  .ContentLayout-text
      = f.text_field :name, class: 'InputText', required: true
  .ContentLayout-label
    = f.label :event_hashtag, class: 'Label'
  .ContentLayout-text
    = f.text_field :hashtag, class: 'InputText InputText--small'
  .ContentLayout-label
    = f.label :event_description, class: 'Label'
  .ContentLayout-text
    = f.text_field :description, class: 'InputText'
  .ContentLayout-label
    = f.label :start_date, class: 'Label'
  .ContentLayout-text
    = f.datetime_select :start_date, { minute_step: 15, required: true }, { class: 'InputDropdown' }
  .ContentLayout-label
    = f.label :location, class: 'Label'
  .ContentLayout-text
    = f.text_field :location, required: true, class: 'InputText'
  .ContentLayout-label
    = f.label :event_interests, class: 'Label'
  .ContentLayout-text
    = f.text_field :interest_list, value: @event.interest_list.join(','), class: 'InputText'

app/views/events/edit.slim
.BodyLayout
  .BodyLayout-header
    .BodyLayout-headerItemCenter
      .Heading.Heading--large Creating Event
  .BodyLayout-content
    .ContentLayout.ContentLayout--form
      = form_for @event do |f|
        = render partial: 'fields', locals: {f: f}
        .ContentLayout-action
          = f.submit 'save', class: 'Button'

app/views/events/index.slim
.BodyLayout
  .BodyLayout-header
    .BodyLayout-headerItemLeft
      -if current_user.present?
        = link_to 'New Event', new_event_path, class: 'Button Button--awesome'
    .BodyLayout-headerItemCenter
      Heading.Heading--large Events
  -@events_per_month.each do |month|
    .BodyLayout-content
      Heading.Heading--small
        =Date::MONTHNAMES[month[0]]
      .Separator
      ul.Grid
        -month[1].each do |event|
          li.Grid-item
            .Event
              = link_to event_path(event.id) do
                .Event-title = event.name
                .Event-label = event.hashtag
                .Event-primaryInfo = "On #{Date::DAYNAMES[event.start_date.wday]} #{event.starting_date}"
                .Event-secondaryInfo = event.location
                .Event-primaryInfo About
                .Event-primaryInfo = event.attendees.size

app/views/events/new.slim
.BodyLayout
  .BodyLayout-header
    .BodyLayout-headerItemCenter
      .Heading.Heading--large Creating Event
  .BodyLayout-content
    .ContentLayout.ContentLayout--form
      = form_for @event do |f|
        = render partial: 'fields', locals: {f: f}
        .ContentLayout-action
          = f.submit 'save', class: 'Button'

app/views/events/show.slim
.BodyLayout
  .BodyLayout-header
    .BodyLayout-headerItemCenter
      .Heading.Heading--large = @event.name
  .BodyLayout-content
    .Grid.Grid--threeColumns
      .Grid-item
        .Separator
        .ContentLayout
          .ContentLayout-label
            .Label Hashtag
          .ContentLayout-text
            = @event.hashtag
          .ContentLayout-label
            .Label Description
          .ContentLayout-text
            = @event.description
      .Grid-item
        .Separator
        .ContentLayout
          .ContentLayout-label
            .Label Start time
          .ContentLayout-text
            = @event.start_date
          .ContentLayout-label
            .Label Date
          .ContentLayout-text
            = @event.start_date
          .ContentLayout-label
            .Label Location
          .ContentLayout-text
            = @event.location
      .Grid-item
        .Separator
        .ContentLayout
          .ContentLayout-label
            .Label Interests
          .ContentLayout-text
            -@event.interest_list.each do |interest|
              = "#{interest}"
          .ContentLayout-label
            .Label Attending
          .ContentLayout-text
            = "#{@event.attendees.size}"
  .BodyLayout-headerItemCenter
    -if current_user.present?
      - if @event.attending?(current_user.id)
        = link_to 'Attend', attend_event_path(@event), method: :post, class: 'Button Button--super'
      - else
        = link_to 'Cancel', cancel_attend_event_path(@event), method: :delete, class: 'Button Button--super'
    -else
      = link_to 'Sign in with your twitter account', user_omniauth_authorize_path(:twitter)
    - if can? :manage, @event
      = link_to 'Edit Event', edit_event_path(@event), class: 'Button'
      = link_to 'Delete Event', event_path(@event), method: :delete, class: 'Button'